#+TITLE: Peak Performance
#+STARTUP: indent

[[./peak-performance.html][HTML Export]]

* Foreword
The two authors of this book have been stellar in their careers. Steve was an athlete who ran a 4 minute 1 second mile 
at the age of 18 simulataneously beating professional athletes. He now works as a endurance sports coach. Brad was a
consultant at McKinsey who developed a great statistical model for healthcare and insurance companies at the of 24 
that was eventually used by the White House where Brad went to work for the President. Both of them have had highly
successful careers, reached their peak level of performance, and burnt out. With this book their intent is to teach 
sustainable methods to reach peak performance without burning out.

* Introduction
In recent times competition has increased in every field and so has the pressure to perform. The number of hours
Americans put in every week has gone up from the past few decades; a study concluded that on average an American works
47 hours per week instead of 40. Additionally, Americans sleep less than the global average.

People have stared using drugs to cope with this. The sales of x hour energy drinks and attention enhancing drugs are 
going up. Students have started using it to improve focus and scores. Professionals use it increase productivity. And
the use of performance enhancing drugs in sports is well-known. Non-professional athletes participating in weekend
events have also started using it pushing sports organizers to test them for such drugs.

However, performance enhancement drug use for improving performance is an unsustainable apporach in any field. Champions
in various fields follow a sustainable approach. This books describes that approach with suggestions on how to apply it
in ones life. 

* The Growth Equation

** The Secret To Sustainable Success
The growth formula : *Stress + Rest = Growth*

This seemingly simple formula is used by champions to reach peak levels of performance. An athlete named Deena Kastor who
has won Olympic bronze medal in marathon running for America is an ideal example of the stress + rest philisophy. She
was an average athlete in collegiate sports but was still able to achieve highest levels of performance. Becaue of her
passion for sports she started her journey after college by hiring a coach with whom she trained in high altitude
regions of Colorado and California. What is important to note however is her discipline and schedule during those years
in training. 

  start running who runs marathons at 40. bronze medalist, marathon at average 5 min some seconds in
olympics and still 5 min some seconds at the age of 40; her training; average athlete in college but moved to high
altitudes in colorado and then california, trained there everyday with about 120-150 miles run per week. but her secret
to sustained performance from early years to today at age of over 40 is her rest schedule 10-12 hours of sleep, yoga,
meditation, massage etc. kenyan athletes train similarly with intense workout day followed by light or no workout day.

creative people. researchers have found that they too follow stress-rest cycles. exhaustion, incubation, insight.

resisting something is also stress which exhausts mental muscle e.g. cookies and raddish experiment. it proves few
things; 1. mind is a muscle. 2. exhaustion on one task carries forward in other task. 3. however, since it is a muscle
it can be trained to do anything like resisting cookies, increasing will power etc. they key is to train it everyday,
start with a simpler/small task/challenge, train to the point of exhaustion, then rest and repeat with better/harder
challenge/task. 

Must put enough stress before rest to a breaking point. but you must rest. find the right balance of stress and
rest. too much stress results in fatigue and burnout. too much rest doesnt lead to growth. people who can balance these
become champions.

Chess and tai chi champion. someone who has achieved both physical and mental peak performance. his secret is the
stress+rest cycle. He talks about in his book called "the art of learning".

** Rethinking Stress
Mice

** Stress Yourself

** The Paradox Of Rest

** Rest Like The Best

* Priming

** Optimize Your Routine

** Minimalist To Be Maximalist

* Purpose

** Transcend Your"Self"

** Develop Your Purpose

* Conclusion: Application Is Everything


